# fork = false
# frame = "full"
# idle = true
# maximized = false
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
# no-multigrid = false
# srgb = false
# tabs = true
# theme = "auto"
# title-hidden = true
# vsync = true
# wsl = false

[font]
normal = [ "IosevkaCapy Nerd Font" ]
size = 12.0
